version: "3"


volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/mtravez/data/web
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/mtravez/data/database
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    restart: on-failure
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    restart: on-failure
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    driver: bridge

